[package]
name    = "camproto-ingest"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0" 

[lib]
name = "camproto_ingest"
path = "src/lib.rs"

[[bin]]
name = "dev"
path = "src/bin/dev.rs"

[dependencies]
tokio  = { version = "1.53.1", features = ["full"] }
bytes  = "1.12.1"
url    = "2"
md5    = "0.8.1"
base64 = "0.23.1"
percent-encoding = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace]
