[package]
name    = "camproto-ingest"
version = "0.1.0"
edition = "2021"

[lib]
name = "camproto_ingest"
path = "src/lib.rs"

[[bin]]
name = "dev"
path = "src/bin/dev.rs"

[dependencies]
tokio  = { version = "1", features = ["full"] }
bytes  = "1"
url    = "2"
md5    = "0.8.0"
base64 = "0.22"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }